from __future__ import annotations

"""Utilities for filtering API entries based on documentation quality and safety cues.

This module reads collector-produced JSONL records, applies a sequence of
documentation- and signature-based checks, and writes accepted APIs plus a
summary report. The filtering logic is intentionally heuristic and is preserved
exactly as-is.
"""

import argparse
import csv
import json
import os
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple


# Minimum normalized documentation length before very short docs are treated
# as likely placeholders.
DOC_MIN_CHARS = 40

# Name-based cues that often suggest side effects, external I/O, training,
# state mutation, or environmental dependencies.
SIDE_EFFECT_NAME_PATTERNS = [
    r"\b(save|load|open|read|write|download|upload|export|import|serialize|deserialize)\b",
    r"\b(checkpoint|state_dict)\b",
    r"\b(train|fit|learn|optimizer|backward|grad|gradient)\b",
    r"\b(distributed|cluster|server|worker|rpc|remote)\b",
    r"\b(register|attach|subscribe|listener|callback|hook)\b",
    r"\b(session|scope|graph|global|context)\b",
    r"\b(camera|microphone|audio|video)\b",
]

# Documentation cues that may indicate side effects or dependence on mutable
# global/runtime state.
SIDE_EFFECT_DOC_PATTERNS = SIDE_EFFECT_NAME_PATTERNS + [
    r"\bin-?place\b",
    r"\bmodif(?:y|ies|ied)\b",
    r"\bside effect\b",
    r"\bglobal state\b",
    r"\bcurrent device\b",
    r"\bcurrent stream\b",
    r"\bvolatile state\b",
]

# Parameter-name/type cues that usually imply non-standalone dependencies or
# environment-specific objects rather than simple fuzzable inputs.
BAD_PARAM_NAME_PATTERNS = [
    r"\b(path|filepath|filename|file|dir|directory)\b",
    r"\b(url|uri|http|https|socket|port|host)\b",
    r"\b(device|gpu|tpu|cuda|xla|mps|xpu)\b",
    r"\b(session|graph|scope|context|handle|stream)\b",
    r"\b(model|module|layer|network|optimizer|dataset|dataloader)\b",
    r"\b(callback|hook|listener|subscriber|observer)\b",
    r"\b(cluster|server|worker|rpc|remote)\b",
]

# Tokens considered constructable/fuzzable.
FUZZABLE_TYPE_TOKENS = [
    "int", "integer", "float", "double", "bool", "boolean",
    "str", "string", "bytes",
    "list", "tuple", "dict", "set",
    "sequence", "array", "ndarray", "tensor", "tensors",
    "number", "numeric", "scalar",
    "dtype", "shape",
]

# Tokens considered poor candidates for direct fuzzing due to environmental or
# heavyweight dependencies.
NONFUZZABLE_TYPE_TOKENS = [
    "file", "path", "filepath", "filename", "directory",
    "url", "uri", "socket", "http", "https",
    "device", "gpu", "tpu", "cuda", "camera", "microphone",
    "session", "graph", "scope", "context", "handle", "stream",
    "iterator", "generator", "callable", "function", "callback", "hook", "listener",
    "module", "model", "layer", "optimizer", "dataset", "dataloader",
    "rpc", "remote", "server", "worker", "cluster",
    "environment",
]

# Common section header variants recognized in docstrings.
SECTION_HEADERS = {
    "args": {"args", "arguments", "parameters", "parameter", "inputs", "input"},
    "returns": {"returns", "return", "output", "outputs", "result", "results"},
}

# Exact parameter descriptions considered too generic to be useful.
GENERIC_PARAM_DESC_EXACT = {
    "input",
    "the input",
    "parameter",
    "argument",
    "value",
    "values",
    "object",
    "some object",
    "anything",
    "stuff",
    "data structure",
    "data",
    "the data",
}


@dataclass
class ParamInfo:
    """Structured representation of a documented parameter."""

    name: str
    type: Optional[str]
    desc: str
    optional: bool = False
    default: Optional[str] = None


@dataclass
class ReturnInfo:
    """Structured representation of a documented return value."""

    type: Optional[str]
    desc: str


@dataclass
class Decision:
    """Final decision for one API entry after filtering."""

    accepted: bool
    step: int
    reason: str


def _normalize(s: str) -> str:
    """Normalize whitespace in a string and trim leading/trailing space."""
    return re.sub(r"\s+", " ", (s or "").strip())


def _split_lines(doc: str) -> List[str]:
    """Split text into lines after normalizing newline conventions."""
    return (doc or "").replace("\r\n", "\n").replace("\r", "\n").split("\n")


def _match_any(patterns: List[str], text: str) -> Optional[str]:
    """Return the first regex pattern that matches the lowercased text."""
    t = (text or "").lower()
    for pat in patterns:
        if re.search(pat, t):
            return pat
    return None


def _is_placeholder_doc(doc: str) -> bool:
    """Heuristically detect missing, autogenerated, or placeholder documentation."""
    d = _normalize(doc).lower()
    if not d:
        return True

    head_lines = [ln.strip().lower()
                  for ln in _split_lines(doc)[:6] if ln.strip()]
    head = " ".join(head_lines)

    placeholder_head_patterns = [
        r"\btodo\b",
        r"\btbd\b",
        r"\bfixme\b",
        r"\badd doc\b",
        r"\badd docs\b",
        r"\bno doc(?:string)?\b",
        r"\bplaceholder\b",
        r"\bstub\b",
        r"\bautogenerated\b",
        r"\bgenerated by\b",
    ]
    if any(re.search(p, head) for p in placeholder_head_patterns):
        return True

    if len(d) < DOC_MIN_CHARS:
        if re.fullmatch(r"(pass|\.\.\.|todo|tbd|none|no docstring\.?)", d):
            return True
        if len(re.findall(r"[a-zA-Z0-9]", d)) < 12:
            return True

    has_args = any(line.strip().strip(":").lower()
                   in SECTION_HEADERS["args"] for line in _split_lines(doc))
    has_returns = any(line.strip().strip(":").lower(
    ) in SECTION_HEADERS["returns"] for line in _split_lines(doc))
    if not has_args and not has_returns:
        nonempty = [ln.strip() for ln in _split_lines(doc) if ln.strip()]
        if len(nonempty) <= 2:
            if len(re.findall(r"[.!?]", d)) <= 1 and len(d.split()) < 10:
                return True

    if d in {"", ".", "..", "..."}:
        return True

    return False


def _normalize_param_name(name: str) -> str:
    """Normalize a parameter name by trimming whitespace and leading * markers."""
    name = (name or "").strip()
    name = name.lstrip("*")
    return name.strip()


def _looks_like_new_section(line: str) -> bool:
    """Return whether a line looks like the beginning of a new docstring section."""
    s = line.strip().rstrip(":").lower()
    if s in SECTION_HEADERS["args"] or s in SECTION_HEADERS["returns"]:
        return True
    if re.fullmatch(r"-{3,}", s):
        return True
    if re.fullmatch(r"(raises|examples?|note|notes|warning|warnings|see also|references?)", s):
        return True
    return False


def _parse_google_style_fields(doc_lines: List[str], start_idx: int) -> List[Tuple[str, Optional[str], str, bool]]:
    """Parse Google-style parameter entries from a docstring section."""
    out = []
    i = start_idx + 1
    current = None
    while i < len(doc_lines):
        line = doc_lines[i]
        if not line.strip():
            i += 1
            continue
        if _looks_like_new_section(line):
            break
        if len(line) - len(line.lstrip(" ")) < 2 and not line.startswith("\t"):
            break

        m = re.match(
            r"^\s*(\*{0,2}[A-Za-z_][\w\.]*)\s*(\(([^)]*)\))?\s*:\s*(.*)$", line)
        if m:
            if current:
                name, typ, desc_parts, optmeta = current
                out.append((name, typ, _normalize(
                    " ".join(desc_parts)), optmeta))
            name = _normalize_param_name(m.group(1))
            meta = (m.group(3) or "").strip()
            typ = meta if meta else None
            optmeta = "optional" in meta.lower()
            desc = m.group(4).strip()
            current = (name, typ, [desc] if desc else [], optmeta)
        else:
            if current:
                current[2].append(line.strip())
        i += 1

    if current:
        name, typ, desc_parts, optmeta = current
        out.append((name, typ, _normalize(" ".join(desc_parts)), optmeta))
    return out


def _parse_numpy_parameters(doc_lines: List[str], header_idx: int) -> List[Tuple[str, Optional[str], str, bool]]:
    """Parse NumPy-style parameter entries from a docstring section."""
    i = header_idx + 1
    if i < len(doc_lines) and re.fullmatch(r"\s*-{3,}\s*", doc_lines[i]):
        i += 1

    out = []
    current = None
    while i < len(doc_lines):
        line = doc_lines[i]
        if not line.strip():
            i += 1
            continue
        if _looks_like_new_section(line) and current:
            break
        m = re.match(r"^\s*(\*{0,2}[A-Za-z_][\w\.]*)\s*:\s*(.+?)\s*$", line)
        if m:
            if current:
                name, typ, desc_parts, optmeta = current
                out.append((name, typ, _normalize(
                    " ".join(desc_parts)), optmeta))
            name = _normalize_param_name(m.group(1))
            typ = m.group(2).strip()
            optmeta = "optional" in typ.lower()
            current = (name, typ, [], optmeta)
        else:
            if current:
                current[2].append(line.strip())
        i += 1

    if current:
        name, typ, desc_parts, optmeta = current
        out.append((name, typ, _normalize(" ".join(desc_parts)), optmeta))
    return out


def _parse_rest_params(doc: str) -> List[Tuple[str, Optional[str], str, bool]]:
    """Parse reStructuredText-style ``:param:`` and ``:type:`` fields."""
    out = []
    param_desc: Dict[str, str] = {}
    param_type: Dict[str, str] = {}

    for m in re.finditer(r":param\s+([A-Za-z_]\w*)\s*:\s*(.+)", doc):
        param_desc[m.group(1)] = _normalize(m.group(2))
    for m in re.finditer(r":type\s+([A-Za-z_]\w*)\s*:\s*(.+)", doc):
        param_type[m.group(1)] = _normalize(m.group(2))

    for name, desc in param_desc.items():
        typ = param_type.get(name)
        opt = "optional" in (typ or "").lower() or "optional" in desc.lower()
        out.append((name, typ, desc, opt))
    return out


def _parse_dash_bullet_params(doc_lines: List[str]) -> List[Tuple[str, Optional[str], str, bool]]:
    """Parse simple dash- or bullet-based parameter lines."""
    out = []
    pat = re.compile(
        r"^\s*[-*]?\s*(\*{0,2}[A-Za-z_][\w\.]*)\s*(\(([^)]*)\))?\s*[–-]\s*(.+?)\s*$")
    for line in doc_lines:
        m = pat.match(line)
        if not m:
            continue
        name = _normalize_param_name(m.group(1))
        meta = (m.group(3) or "").strip()
        typ = meta if meta else None
        desc = _normalize(m.group(4))
        opt = "optional" in (meta or "").lower() or "optional" in desc.lower()
        out.append((name, typ, desc, opt))
    return out


def parse_params_from_doc(doc: str) -> List[ParamInfo]:
    """Extract documented parameters from a docstring using several style parsers."""
    lines = _split_lines(doc)

    arg_idx = None
    for i, line in enumerate(lines):
        h = line.strip().strip(":").lower()
        if h in SECTION_HEADERS["args"]:
            arg_idx = i
            break

    params: List[Tuple[str, Optional[str], str, bool]] = []
    if arg_idx is not None:
        params = _parse_google_style_fields(lines, arg_idx)

    if not params:
        for i, line in enumerate(lines):
            if line.strip().lower() == "parameters":
                params = _parse_numpy_parameters(lines, i)
                break

    if not params:
        params = _parse_rest_params(doc)

    if not params:
        params = _parse_dash_bullet_params(lines)

    out: List[ParamInfo] = []
    for name, typ, desc, optmeta in params:
        if not name or name.startswith("_"):
            continue
        out.append(
            ParamInfo(
                name=name,
                type=_normalize(typ) if typ else None,
                desc=_normalize(desc),
                optional=bool(optmeta),
            )
        )
    return out


def parse_signature_params(sig: Optional[str]) -> List[Tuple[str, bool, Optional[str]]]:
    """Parse a textual function signature into parameter names and default info."""
    if not sig:
        return []

    s = sig.strip()
    if "\n" in s:
        s = s.split("\n", 1)[0].strip()
    if "(" in s and ")" in s:
        s = s[s.find("(") + 1: s.rfind(")")]

    parts: List[str] = []
    depth = 0
    cur: List[str] = []

    for ch in s:
        if ch == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
            continue
        cur.append(ch)
        if ch in "([{":
            depth += 1
        elif ch in ")]}" and depth > 0:
            depth -= 1

    if cur:
        parts.append("".join(cur).strip())

    out: List[Tuple[str, bool, Optional[str]]] = []
    for p in parts:
        if not p or p in {"*", "/"}:
            continue
        name = p
        default = None
        has_default = False
        if "=" in p:
            name, default = [x.strip() for x in p.split("=", 1)]
            has_default = True
        if ":" in name:
            name = name.split(":", 1)[0].strip()
        name = name.lstrip("*")
        if not name:
            continue
        out.append((name, has_default, default))

    return out


def _parse_numpy_returns(doc_lines: List[str], header_idx: int) -> Optional[ReturnInfo]:
    """Parse a NumPy-style returns section."""
    i = header_idx + 1
    if i < len(doc_lines) and re.fullmatch(r"\s*-{3,}\s*", doc_lines[i]):
        i += 1

    while i < len(doc_lines) and not doc_lines[i].strip():
        i += 1
    if i >= len(doc_lines):
        return None

    first = doc_lines[i].strip()
    rtype = None
    rdesc_lines: List[str] = []

    m = re.match(r"^([A-Za-z_][\w\.]*)\s*:\s*(.+)$", first)
    if m:
        rtype = _normalize(m.group(2))
    else:
        rtype = _normalize(first)

    i += 1
    while i < len(doc_lines):
        line = doc_lines[i]
        if not line.strip():
            i += 1
            continue
        if _looks_like_new_section(line):
            break
        if len(line) - len(line.lstrip(" ")) < 2 and not line.startswith("\t"):
            break
        rdesc_lines.append(line.strip())
        i += 1

    desc = _normalize(" ".join(rdesc_lines))
    if not desc:
        return None
    return ReturnInfo(type=rtype, desc=desc)


def parse_return_from_doc(doc: str) -> Optional[ReturnInfo]:
    """Extract return information from a docstring using several style parsers."""
    lines = _split_lines(doc)

    ret_idx = None
    for i, line in enumerate(lines):
        h = line.strip().strip(":").lower()
        if h in SECTION_HEADERS["returns"]:
            ret_idx = i
            break

    if ret_idx is not None:
        i = ret_idx + 1
        collected: List[str] = []
        rtype = None
        while i < len(lines):
            line = lines[i]
            if not line.strip():
                i += 1
                continue
            if _looks_like_new_section(line):
                break
            if len(line) - len(line.lstrip(" ")) < 2 and not line.startswith("\t"):
                break
            collected.append(line.strip())
            i += 1

        text = _normalize(" ".join(collected))
        if text:
            m = re.match(r"^([^:]{1,60})\s*:\s*(.+)$", text)
            if m:
                rtype = _normalize(m.group(1))
                rdesc = _normalize(m.group(2))
            else:
                rdesc = text
            if rdesc:
                return ReturnInfo(type=rtype, desc=rdesc)

    for i, line in enumerate(lines):
        if line.strip().lower() == "returns":
            ri = _parse_numpy_returns(lines, i)
            if ri:
                return ri

    m = re.search(r":returns?\s*:\s*(.+)", doc)
    if m:
        desc = _normalize(m.group(1))
        if desc:
            return ReturnInfo(type=None, desc=desc)

    first = next((l.strip() for l in lines if l.strip()), "")
    m = re.search(r"->\s*([A-Za-z0-9_.:\[\]]+)", first)
    if m:
        rtype = _normalize(m.group(1))
        summary = _normalize(" ".join([l.strip()
                             for l in lines[1:10] if l.strip()]))
        if summary:
            return ReturnInfo(type=rtype, desc=summary[:600])

    return None


def _step_name(step: int) -> str:
    """Map a numeric rejection step to its summary key."""
    return {
        1: "1_doc",
        2: "2_params",
        3: "3_types",
        4: "4_side_effects",
        5: "5_return",
    }.get(step, f"{step}_unknown")


def _api_leaf(api: str) -> str:
    """Return the final dotted component of a fully qualified API name."""
    return (api or "").rsplit(".", 1)[-1]


def _api_parent(api: str) -> str:
    """Return the parent dotted path of a fully qualified API name."""
    return (api or "").rsplit(".", 1)[0] if "." in (api or "") else ""


def _base_alias_name(api: str) -> str:
    """Return the non-inplace alias name for an API ending in a trailing underscore."""
    parent = _api_parent(api)
    leaf = _api_leaf(api)
    if leaf.endswith("_") and len(leaf) > 1:
        leaf = leaf[:-1]
    return f"{parent}.{leaf}" if parent else leaf


def _type_tokens(type_str: Optional[str], desc: str, name: str) -> str:
    """Combine type, description, and name into a lowercase searchable token string."""
    combined = " ".join([type_str or "", desc or "", name or ""])
    combined = combined.replace(":class:`", "").replace(
        "`", "").replace("'", "")
    return combined.lower()


def _is_exception_like(entry: Dict[str, Any]) -> bool:
    """Return whether an entry appears to represent a class or exception-like API."""
    api = entry.get("api") or entry.get("qualname") or ""
    leaf = _api_leaf(api)
    kind = (entry.get("kind") or "").lower()
    if kind == "class":
        return True
    if re.search(r"(Error|Exception|Warning)$", leaf):
        return True
    return False


def _is_inplace_name(api: str) -> bool:
    """Return whether an API name follows the trailing-underscore inplace style."""
    leaf = _api_leaf(api)
    return bool(leaf.endswith("_") and not leaf.startswith("__"))


def _is_vague_param_desc(desc: str) -> bool:
    """Return whether a parameter description is too generic to be informative."""
    d = _normalize(desc).lower()
    if not d:
        return True
    if d in GENERIC_PARAM_DESC_EXACT:
        return True
    if re.fullmatch(r"(the\s+)?(input|parameter|argument|value|object|data)\.?", d):
        return True
    if re.fullmatch(r"(some|any)\s+(object|value|data|thing)\.?", d):
        return True
    if re.search(r"\b(anything|stuff|data structure)\b", d):
        return True
    return False


def _is_vague_return_desc(ret: ReturnInfo) -> bool:
    """Return whether a return description is too vague to be useful."""
    d = _normalize(ret.desc).lower()
    t = _normalize(ret.type or "").lower()
    if not d:
        return True

    typed_text = f"{t} {d}".strip()
    if re.search(r"\b(tensor|tensors|array|ndarray|tuple|list|dict|scalar|number|numeric|string|bool|int|float)\b", typed_text):
        return False

    if d in {"returns", "output", "result", "a result"}:
        return True
    if re.fullmatch(r"(returns?\s+)?(something|value|values|object|objects)\.?", d):
        return True

    return False


def is_fuzzable_param(p: ParamInfo) -> Tuple[bool, str]:
    """Determine whether a parameter looks constructable enough for fuzzing."""
    tokens = _type_tokens(p.type, p.desc, p.name)

    for bad in NONFUZZABLE_TYPE_TOKENS:
        if re.search(rf"\b{re.escape(bad)}\b", tokens):
            return False, f"non-fuzzable type cue: {bad}"

    for good in FUZZABLE_TYPE_TOKENS:
        if re.search(rf"\b{re.escape(good)}\b", tokens):
            return True, f"fuzzable type cue: {good}"

    if re.search(r"\b(tensor|ndarray|array|scalar|number|numeric)\b", tokens):
        return True, "fuzzable inferred from description"

    return False, "type unclear / not constructable"


def has_side_effect(api_name: str, doc: str, params: List[ParamInfo]) -> Tuple[bool, str]:
    """Detect whether an API likely has side effects or external dependencies."""
    if _is_inplace_name(api_name):
        return True, "in-place style API name"

    name_hit = _match_any(SIDE_EFFECT_NAME_PATTERNS, api_name)
    if name_hit:
        return True, f"name contains side-effect keyword ({name_hit})"

    doc_head = "\n".join(_split_lines(doc)[:20])
    doc_hit = _match_any(SIDE_EFFECT_DOC_PATTERNS, doc_head)
    if doc_hit:
        return True, f"doc indicates side-effect/external-dependency keyword ({doc_hit})"

    for p in params:
        joined = f"{p.type or ''} {p.desc or ''}"
        if _match_any(BAD_PARAM_NAME_PATTERNS, p.name) or _match_any(BAD_PARAM_NAME_PATTERNS, joined):
            if re.search(r"\b(callback|hook|listener|subscribe)\b", p.name.lower()):
                if p.optional:
                    continue
                return True, f"required callback-like param '{p.name}'"
            if p.optional:
                continue
            return True, f"external-dep param cue '{p.name}'"

    return False, ""


def is_bad_return(doc: str, ret: ReturnInfo) -> bool:
    """Detect return descriptions that imply None, inplace mutation, or global-state behavior."""
    d = (ret.desc or "").lower()
    t = (ret.type or "").lower()
    full = f"{doc}\n{ret.desc}".lower()

    if re.search(r"\bnone\b", d) or t == "none":
        return True
    if _match_any(
        [
            r"\bin-?place\b",
            r"\bside effect\b",
            r"\bglobal state\b",
            r"\bcurrent device\b",
            r"\bcurrent stream\b",
            r"\bvolatile state\b",
            r"\bmodif(?:y|ies|ied)\b",
        ],
        full,
    ):
        return True
    return False


def collapse_inplace_aliases(rows: List[Dict[str, str]]) -> List[Dict[str, str]]:
    """Remove inplace-style aliases when a corresponding base API is also present."""
    by_api = {r.get("api_full_name", ""): r for r in rows}
    dropped = set()

    for api in list(by_api.keys()):
        leaf = _api_leaf(api)
        if not leaf.endswith("_"):
            continue
        base_api = _base_alias_name(api)
        if base_api in by_api:
            dropped.add(api)

    out = [r for r in rows if r.get("api_full_name", "") not in dropped]
    out.sort(key=lambda r: r.get("api_full_name", ""))
    return out


def filter_one(entry: Dict[str, Any]) -> Tuple[Decision, Dict[str, str]]:
    """Apply the full filtering pipeline to a single API entry."""
    api = entry.get("api") or entry.get("qualname") or ""
    doc = entry.get("doc") or ""

    base_row = {
        "api_full_name": api,
        "api_doc_text": doc,
    }

    resolved = bool(entry.get("resolved", False))
    if not resolved:
        return Decision(False, 1, f"unresolved: {entry.get('error', 'unresolved')}"), base_row

    if _is_placeholder_doc(doc):
        return Decision(False, 1, "missing/placeholder/too short doc"), base_row

    if _is_exception_like(entry):
        return Decision(False, 2, "classes/exceptions are excluded"), base_row

    sig = entry.get("signature")
    sig_params = parse_signature_params(sig)
    doc_params = parse_params_from_doc(doc)

    concrete_sig = [p for p in sig_params if p[0]
                    not in {"self", "cls", "args", "kwargs"}]

    if concrete_sig:
        doc_by_name = {p.name: p for p in doc_params}

        missing = [n for (n, _, _) in concrete_sig if n not in doc_by_name]
        if missing:
            return Decision(False, 2, f"missing param descriptions for: {', '.join(missing[:8])}"), base_row

        vague = [n for (n, _, _) in concrete_sig if _is_vague_param_desc(
            doc_by_name[n].desc)]
        if vague:
            return Decision(False, 2, f"vague param descriptions for: {', '.join(vague[:8])}"), base_row

        required_names = [n for (n, has_default, _)
                          in concrete_sig if not has_default]
        if not required_names:
            return Decision(False, 2, "all parameters are optional; no required documented input"), base_row
    else:
        if not doc_params:
            return Decision(False, 2, "no parsable parameters in doc"), base_row

        vague = [p.name for p in doc_params if _is_vague_param_desc(p.desc)]
        if vague:
            return Decision(False, 2, f"vague param descriptions for: {', '.join(vague[:8])}"), base_row

        required_doc = [p for p in doc_params if not p.optional]
        if not required_doc:
            return Decision(False, 2, "all parameters are optional; no required documented input"), base_row

    doc_by_name = {p.name: p for p in doc_params}
    merged_params: List[ParamInfo] = []

    if sig_params:
        for name, has_def, default in sig_params:
            if name in {"self", "cls"}:
                continue

            dp = doc_by_name.get(name)
            if not dp:
                continue

            merged_params.append(
                ParamInfo(
                    name=dp.name,
                    type=dp.type,
                    desc=dp.desc,
                    optional=bool(dp.optional or has_def),
                    default=default if has_def else None,
                )
            )

        if not merged_params and doc_params:
            merged_params = doc_params
    else:
        merged_params = doc_params

    required_params = [p for p in merged_params if not p.optional]
    if not required_params:
        return Decision(False, 3, "no required constructible parameters found"), base_row

    for p in required_params:
        fuzzable, why = is_fuzzable_param(p)
        if not fuzzable:
            return Decision(False, 3, f"required param '{p.name}' not fuzzable: {why}"), base_row

    se, why = has_side_effect(api_name=api, doc=doc, params=merged_params)
    if se:
        return Decision(False, 4, why), base_row

    ret = parse_return_from_doc(doc)
    if not ret or not ret.desc:
        return Decision(False, 5, "no return description found"), base_row
    if _is_vague_return_desc(ret):
        return Decision(False, 5, "return description is too vague"), base_row
    if is_bad_return(doc, ret):
        return Decision(False, 5, "return indicates side-effect/in-place/None/global-state behavior"), base_row

    return Decision(True, 0, ""), base_row


def read_jsonl(path: str) -> List[Dict[str, Any]]:
    """Read a JSONL file and skip lines that fail to parse."""
    out: List[Dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except Exception:
                continue
    return out


def write_two_col_csv(path: str, rows: List[Dict[str, str]]) -> None:
    """Write accepted rows to a two-column CSV, creating parent directories if needed."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    headers = ["api_full_name", "api_doc_text"]
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=headers)
        w.writeheader()
        for r in rows:
            w.writerow(
                {
                    "api_full_name": r.get("api_full_name", ""),
                    "api_doc_text": r.get("api_doc_text", ""),
                }
            )


def infer_library_name(data: List[Dict[str, Any]], fallback: str = "library") -> str:
    """Infer the library name from the first available API/qualname prefix."""
    for e in data:
        api = e.get("api") or e.get("qualname") or ""
        if api and "." in api:
            return api.split(".", 1)[0]
        if api:
            return api
    return fallback


def main(argv: Optional[List[str]] = None) -> int:
    """Parse arguments, filter entries, and write accepted APIs plus a summary."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True,
                    help="Input JSONL (collector output)")
    ap.add_argument("--outdir", required=True, help="Base output directory")
    ap.add_argument("--lib-name", default="",
                    help="Library name for output folder (default: inferred)")
    ap.add_argument("--max", type=int, default=0,
                    help="Max entries to process (0=all)")
    ap.add_argument("--max-examples", type=int, default=50,
                    help="Max example reasons per step in summary.json")
    args = ap.parse_args(argv)

    data = read_jsonl(args.inp)
    if args.max and args.max > 0:
        data = data[:args.max]

    lib_name = args.lib_name.strip() or infer_library_name(data)
    base = os.path.join(args.outdir, lib_name)

    accepted_raw: List[Dict[str, str]] = []

    summary: Dict[str, Any] = {
        "input": args.inp,
        "library": lib_name,
        "total": 0,
        "accepted": 0,
        "accepted_before_alias_dedup": 0,
        "duplicate_aliases_removed": 0,
        "rejected": 0,
        "rejected_by_step": {_step_name(i): 0 for i in range(1, 6)},
        "top_reasons": {},
        "examples_by_step": {_step_name(i): [] for i in range(1, 6)},
    }

    for entry in data:
        summary["total"] += 1
        decision, row = filter_one(entry)

        if decision.accepted:
            accepted_raw.append(row)
            continue

        summary["rejected"] += 1
        if 1 <= decision.step <= 5:
            sname = _step_name(decision.step)
            summary["rejected_by_step"][sname] += 1
            summary["top_reasons"][decision.reason] = summary["top_reasons"].get(
                decision.reason, 0) + 1

            ex = summary["examples_by_step"][sname]
            if len(ex) < args.max_examples:
                ex.append(
                    {
                        "api_full_name": row.get("api_full_name", ""),
                        "reason": decision.reason,
                    }
                )

    accepted_before_alias_dedup = len(accepted_raw)
    accepted = collapse_inplace_aliases(accepted_raw)

    summary["accepted_before_alias_dedup"] = accepted_before_alias_dedup
    summary["accepted"] = len(accepted)
    summary["duplicate_aliases_removed"] = accepted_before_alias_dedup - \
        len(accepted)

    os.makedirs(base, exist_ok=True)
    write_two_col_csv(os.path.join(base, "accepted.csv"), accepted)

    with open(os.path.join(base, "summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print(
        f"[filter] library={lib_name} total={summary['total']} "
        f"accepted={summary['accepted']} dup_removed={summary['duplicate_aliases_removed']} "
        f"rejected={summary['rejected']}"
    )
    print(f"[filter] wrote: {os.path.join(base, 'accepted.csv')}")
    print(f"[filter] wrote: {os.path.join(base, 'summary.json')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())